#!/bin/bash
### BEGIN INIT INFO
# Provides:       cheesecake
# Required-Start: nginx
# Required-Stop:
# X-Start-Before:
# X-Stop-After:
### END INIT INFO

NAME=cheesecake
EXEC=/usr/bin/cheesecake
PIDFILE=/var/run/cheesecake.pid
DATA=/var/lib/cheesecake/data.json
DATADIR="$(dirname "$DATA")"

[[ -d "$DATADIR" ]] || mkdir -p "$DATADIR"
[[ -f "$DATA" ]] || echo '[]' > "$DATA"

. /lib/lsb/init-functions

case $1 in
    start)
        log_begin_msg "Starting cheesecake"
        start-stop-daemon --start --pidfile "$PIDFILE" --make-pidfile -b --exec "$EXEC" -d /assets -- \
                          -data "$DATA" -conf /etc/nginx/sites-enabled/default -addr ":8080"
        log_end_msg $?
        ;;
    stop)
        log_begin_msg "Stopping cheesecake"
        start-stop-daemon --stop --oknodo --pidfile "$PIDFILE" --name "$NAME" --remove-pidfile
        log_end_msg $?
        ;;
    *)
        echo "Usage: $0 start|stop"
        exit 1
        ;;
esac
